import "./globals.css";
import '@fontsource/kanit';

export const metadata = {
  title: "To Ice 💖",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
